name: CI

on:
  push:
    branches: [ gh-pages ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Decode base64 secrets and deploy to web
    steps:
      - uses: actions/checkout@v2
      - run: echo $OPEN_AI | base64 -d > assets/assets/secrets.json
        env:
          OPEN_AI: ${{ secrets.OPEN_AI }}
